//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoprokat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issued_Cars
    {
        public int ID_Hire { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public Nullable<int> ID_Car { get; set; }
        public Nullable<int> ID_Workers { get; set; }
        public Nullable<System.DateTime> Date_Issue { get; set; }
        public string Quatity_Days { get; set; }
        public Nullable<System.DateTime> Date_Return { get; set; }
        public string Deposit_amount { get; set; }
        public string Amount_Payable { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual WorkersAutoProkat WorkersAutoProkat { get; set; }
    }
}
