
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Autoprokat
{

using System;
    using System.Collections.Generic;
    
public partial class Users
{

    public int ID_User { get; set; }

    public Nullable<int> ID_Role { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }



    public virtual Role Role { get; set; }

}

}
